plugins:
  - jest
  - babel
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: babel-eslint
extends:
  - airbnb-base
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
